# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Install Depedencies
        run: yarn --frozen-lockfile
      - name: Tests
        run: yarn test --collectCoverage
      - name: Build Docs
        run: yarn build-docs
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
      - name: Coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
